encoder:
    in_channels: 3
    resolution: 64
    channels: 128
    channel_multipliers: [1, 2,]
    z_channels: 3
    num_res_blocks: 2
    dropout: 0.0
    
decoder:
    in_channels: 3
    out_channels: 3
    resolution: 64
    channels: 128
    channel_multipliers: [1, 2, ]
    z_channels: 6
    num_res_blocks: 2
    dropout: 0.0

vae:
    embed_dim: 3
    kld_weight: 1e-6

sampler:
    beta: 'linear'
    T: 1000
    ddim_T: 100
    ddim_eta: 1

unet:
    dim: 64
    dim_mults: [1, 2, 4, 8]
    channels: 3
